### ISSUE TITLE
Pagination problem behind SSL proxy

### ISSUE THREAD

**Issue by bhagemeier** [gnocchixyz/python-gnocchiclient#102]
Hi there,

I seem to have found a problem with pagination when Gnocchi API is behind an SSL proxy. I am using the openstack commandline tool which delegates to python-gnocchiclient. When trying to list 1000 metrics, everything works as expected. Starting at 1001, the connection is closed, apparently because of pagination.

The failing command I use is:

```
$ openstack metric list --limit 1001
gnocchiclient.exceptions.ConnectionFailure: Unable to establish connection to http://hdf-cloud.fz-juelich.de:8041/v1/metric?limit=1000&marker=145db285-c4d0-47f4-ae1d-0ae54480a580&sort=id%3Aasc: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

When running in debug mode, the failing API call is:

```
REQ: curl -g -i -X GET http://hdf-cloud.fz-juelich.de:8041/v1/metric?limit=1000&marker=145db285-c4d0-47f4-ae1d-0ae54480a580&sort=id%3Aasc -H "Accept: applica
tion/json, */*" -H "User-Agent: openstacksdk/0.22.0 keystoneauth1/3.11.2 python-requests/2.21.0 CPython/3.5.3" -H "X-Auth-Token: *******"
```

Please observe the plain HTTP URL. In contrast, the first call to the API, prior to the one above, is done using an HTTPS URL:

```
REQ: curl -g -i -X GET https://hdf-cloud.fz-juelich.de:8041/v1/metric?limit=1001 -H "Accept: application/json, */*" -H "User-Agent: openstacksdk/0.22.0 keyst
oneauth1/3.11.2 python-requests/2.21.0 CPython/3.5.3" -H "X-Auth-Token: ******"
```

I am not sure about the origin of this behavior, but clearly all API calls should be done using the same protocol.

Best regards,
Björn

**Comment by jd** [comment]
This is because the URL sent by Gnocchi contains `http://`. Gnocchi generates this URL because your Web server runs HTTP and I imagine you have a SSL proxy in front of it.

You need to pass the right header between your HTTPS proxy and your HTTP server: https://en.wikipedia.org/wiki/X-Forwarded-For

**Comment by bhagemeier** [comment]
Thanks for the feedback. My entire deployment of OpenStack and thus Gnocchi has been done using kolla-ansible. The SSL terminating proxy is HAProxy, which is configured with "option forwardfor" as part of its "defaults". This should do precisely what you are describing. Comparing the HAProxy configuration section of gnocchi_api_external with that of keystone_api_external, I am missing two lines for Gnocchi.

```
http-request del-header X-Forwarded-Proto if { ssl_fc }
http-request set-header X-Forwarded-Proto https if { ssl_fc }
```

However, adding them and restarting all HAProxies does not help, nor make any difference.

I do see something that could be a related issue: gnocchixyz/grafana-gnocchi-datasource/issues/49, because I am also trying to use the Gnocchi DataSource in Grafana and do see issues there.

All this used to work until two weeks ago. I am not sure whether this is just because of passing the threshold of 1000 metrics or because I reconfigured my OpenStack deployment with a newer version of kolla-ansible. However, acc. to commit messages, nothing changed in the area of Gnocchi between the previous version that I ran successfullly and the version I am now using.

**Comment by jd** [comment]
Did you enable `enable_proxy_headers_parsing`?

**Comment by bhagemeier** [comment]
Thank you so much. The two measures together did the trick. I added 

```
[oslo_middleware]
enable_proxy_headers_parsing = True
```

in gnocchi.conf for the API. Also, I added the two lines mentioned above to haproxy.cfg:

```
http-request del-header X-Forwarded-Proto if { ssl_fc }
http-request set-header X-Forwarded-Proto https if { ssl_fc }
```

I'll have to see whether I made a mistake in my setup, but this may well be worth an entry in the kolla-ansible tracker. After all, it is all supposed to work out of the box.

**Comment by jd** [comment]
Agreed, Kolla should take care of that. :)
