### ISSUE TITLE
gnocchi.xyz down?

### ISSUE THREAD

**Issue by erickonradmiller** [gnocchixyz/python-gnocchiclient#106]
Looks like the domain does not resolve anymore.  Seems like the only place to view the documentation for Gnocchi.  Or is it available somewhere else?

Thanks!

Eric

**Comment by jd** [comment]
See https://github.com/gnocchixyz/gnocchi/issues/1048

**Comment by tobias-urdin** [comment]
https://gnocchi.osci.io/ closing
