### ISSUE TITLE
Access to gnocchiclient on Pypi

### ISSUE THREAD

**Issue by tobias-urdin** [gnocchixyz/python-gnocchiclient#128]
I need access to gnocchiclient on Pypi to make it possible to release new versions.

**Comment by tobias-urdin** [comment]
@jd please add me to maintainers for gnocchiclient https://pypi.org/project/gnocchiclient/

**Comment by tobias-urdin** [comment]
thanks you @jd 👍

**Comment by jd** [comment]
Done
