### ISSUE TITLE
Stop raising Keystone exceptions for connection errors

### ISSUE THREAD

**Issue by larsks** [gnocchixyz/python-gnocchiclient#27]
When gnocchiclient is unable to connect to a given endpoint, it raises a Keystone exception:

```
$ gnocchi --endpoint http://localhost:8888 metric list --debug
[...]
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://localhost:8888/v1/metric?: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /v1/metric (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0863a09750>: Failed to establish a new connection: [Errno 111] Connection refused',))

```

This doesn't make any sense, because there were no Keystone operations involved in this connection. If I wanted to handle this exception, I would need to import the keystone client into my code which otherwise has nothing to do with keystone.

**Comment by jd** [comment]
Yup, we should wrap them.
