### ISSUE TITLE
measures show don't have result.

### ISSUE THREAD

**Issue by yjLiInSky** [gnocchixyz/python-gnocchiclient#38]
I can get the resource list and metric list.  when i use gnocchi measures show , there is no response.  The gnocchi storage  driver is "file".  Can someone help me? thanks.

**Comment by jd** [comment]
Not unless you provide a detailed output of what you did – _as requested when opening this issue_.

**Comment by yjLiInSky** [comment]
when i use the command "measures show", return a blank line and have nothing . I use the file as gnocchi storage driver. I find the measure in file is messy code, is that the reason? 
So thanks!

**Comment by jd** [comment]
Did you send measures…? How? Do you have metricd running?…

**Comment by yjLiInSky** [comment]
@juldanjou hello, i have a problem about gnocchi. I use the archive policy low. for example, points: 12,granularity: 0:05:00,timespan: 1:00:00.  when the time over the timespan 1 hour, the old measures will be deleted? 
Do you understand what i mean? If i install the eviroment at 7:00, and now at 10:00, there is 3 timesapn. how the 12 points of measure will be stored? Is it the measures 7:00 to 8:00, or 8:00 to 9:00, or 9:00 to 10:00?
Can you help me,thanks.

**Comment by jd** [comment]
It will keep 12 points top, that's what it means. It's actually in the doc: http://gnocchi.xyz/operating.html#how-to-define-archive-policies

**Comment by chungg** [comment]
close?
